require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe BookmarksController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Bookmark. As you add validations to Bookmark, be sure to
  # adjust the attributes here as well.
  let(:valid_user) do
    User.create(name: "test", email: "test@test.com", password: "testing")
  end

  let(:valid_attributes) do
    {title: 'bookmark_title', url: 'url.com', user: valid_user}
  end

  let(:invalid_attributes) { {url: ''} }

  before do
    sign_in valid_user
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BookmarksController. Be sure to keep this updated too.
  #let(:valid_session) { {} }

  describe "GET #index" do
    it "returns a success response" do
      bookmark = Bookmark.create! valid_attributes
      #binding.pry
      get :index, params: {user: valid_user}
      expect(response).to be_successful?
    end
  end

  describe "GET #show" do
    it "returns a success response" do
      bookmark = Bookmark.create! valid_attributes
      get :show, params: {id: bookmark.to_param}
      expect(response).to be_successful?
    end
  end

  describe "GET #new" do
    it "returns a success response" do
      get :new, params: {}
      expect(response).to be_successful?
    end
  end

  describe "GET #edit" do
    it "returns a success response" do
      bookmark = Bookmark.create! valid_attributes
      get :edit, params: {id: bookmark.to_param}
      expect(response).to be_successful?
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Bookmark" do
        expect {
          post :create, params: {bookmark: valid_attributes}
        }.to change(Bookmark, :count).by(1)
      end

      it "redirects to the created bookmark" do
        post :create, params: {bookmark: valid_attributes}
        expect(response).to redirect_to(root_path)
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'new' template)" do
        post :create, params: {bookmark: invalid_attributes}
        expect(response).to be_successful?
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        {url: 'dog.com'}
      }

      it "updates the requested bookmark" do
        bookmark = Bookmark.create! valid_attributes
        put :update, params: {id: bookmark.to_param, bookmark: new_attributes}
        bookmark.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the bookmark" do
        bookmark = Bookmark.create! valid_attributes
        put :update, params: {id: bookmark.to_param, bookmark: valid_attributes}
        expect(response).to redirect_to(bookmark)
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'edit' template)" do
        bookmark = Bookmark.create! valid_attributes
        put :update, params: {id: bookmark.to_param, bookmark: invalid_attributes}
        expect(response).to be_successful?
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested bookmark" do
      bookmark = Bookmark.create! valid_attributes
      expect {
        delete :destroy, params: {id: bookmark.to_param}
      }.to change(Bookmark, :count).by(-1)
    end

    it "redirects to the bookmarks list" do
      bookmark = Bookmark.create! valid_attributes
      delete :destroy, params: {id: bookmark.to_param}
      expect(response).to redirect_to(bookmarks_url)
    end
  end

end
